export const GET_CATEGORIES = "GET_POSTS";
export const GET_CATEGORIES_SUCCESS = "GET_POSTS_SUCCESS";
export const GET_CATEGORIES_FAIL = "GET_POSTS_FAIL";
export const CHECK_CATEGORY = "CHECK_CATEGORY";
export const CHECK_CATEGORY_SUCCESS = "CHECK_CATEGORY_SUCCESS";
